user: smartdom
opt: /opt/smartdom
home: /home/smartdom

network:
  vlan_id: 10
  adapter: eth0
  subnet: 192.169.66.1/24
  gateway: 192.169.66.1

proxy:
  domain: smartdom.si
  subdomains: [home, zigbee, docker, tv, torrent]
  ip: 192.168.66.5

mqtt:
  server: mqtt://mosquitto:1883
  users: [zigbee2mqtt, homeassistant]

zigbee2mqtt:
  permit_join: true
  serial:
    port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20240124101335-if00
    adapter: ember
  advanced:
    channel: 17

wireguard:
  port: 54201
  address: 10.0.2.4
  peers:
    - name: phone
      allowed_ips: 192.168.0.0/24,10.0.0.0/8
      persistent_keepalive: 25