---
- name: Create security directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/vaultwarden/data
    - /opt/wireguard/config

- name: Create Vaultwarden container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - /opt/vaultwarden/data:/data
    networks:
      - name: proxy

- name: Create WireGuard container
  docker_container:
    name: wireguard-server
    image: linuxserver/wireguard
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Berlin"
    volumes:
      - /opt/wireguard/config/wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules:ro
    ports:
      - "54201:54201/udp"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: "1"
    networks:
      - name: public
        ipv4_address: "192.168.66.9" 